In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]],dtype=np.uint8)

In [3]:
a.tostring()

b'\x01\x02\x03\x04'

In [4]:
a.tostring(order='F')

b'\x01\x03\x02\x04'

In [5]:
s=a.tostring()
a=np.fromstring(s,dtype=np.uint8)
a

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


array([1, 2, 3, 4], dtype=uint8)

In [7]:
s=a.tostring()
a=np.frombuffer(s,dtype=np.uint8)
a

array([1, 2, 3, 4], dtype=uint8)

In [8]:
a.shape=2,2

In [9]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [11]:
"""
对于文本文件，推荐使用loadtxt,genfromtxt,savetxt
对于二进制文本文件，推荐使用save,load,savez
"""

'\n对于文本文件，推荐使用loadtxt,genfromtxt,savetxt\n对于二进制文本文件，推荐使用save,load,savez\n'

In [ ]:
"""
数组与字符串转换有两种方法
tostirng方法及fromstring/frombuffer方法
"""