In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = array([[1,2,3], [4,5,6]])

In [3]:
sum(a)

21

In [4]:
sum(a,axis=0)

array([5, 7, 9])

In [5]:
sum(a,axis=-1)

array([ 6, 15])

In [6]:
a.sum()

21

In [7]:
a.sum(axis=0)

array([5, 7, 9])

In [8]:
a.sum(axis=-1)

array([ 6, 15])

In [9]:
a.prod()

720

In [10]:
prod(a, axis=0)

array([ 4, 10, 18])

In [11]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
a

array([[0.481, 0.674, 0.747, 0.499],
       [0.534, 0.898, 0.029, 0.13 ],
       [0.668, 0.256, 0.13 , 0.18 ]])

In [12]:
a.min()

0.028602964310706303

In [13]:
a.min(axis=0)

array([0.481, 0.256, 0.029, 0.13 ])

In [14]:
a.max()

0.898239623765466

In [15]:
a.max(axis=-1)

array([0.747, 0.898, 0.668])

In [16]:
a.argmin()

6

In [17]:
a.argmin(axis=0)

array([0, 2, 1, 1], dtype=int64)

In [18]:
a = array([[1,2,3],[4,5,6]])

In [19]:
a.mean()

3.5

In [20]:
a.mean(axis=-1)

array([2., 5.])

In [21]:
mean(a)

3.5

In [22]:
average(a, axis = 0)

array([2.5, 3.5, 4.5])

In [23]:
average(a, axis = 0, weights=[1,2])

array([3., 4., 5.])

In [24]:
a.std(axis=1)

array([0.816, 0.816])

In [25]:
a.var(axis=1)

array([0.667, 0.667])

In [26]:
var(a, axis=1)

array([0.667, 0.667])

In [27]:
std(a, axis=1)

array([0.816, 0.816])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.clip(3,5)   #小于3的变成3，大于5的变成5

array([[3, 3, 3],
       [4, 5, 5]])

In [30]:
a.ptp(axis=1)  #计算最大值和最小值之差

array([2, 2])

In [31]:
a.ptp()

5

In [32]:
a=array([1.35,2.5,1.5])

In [33]:
a.round()

array([1., 2., 2.])

In [34]:
a.round(decimals=1)

array([1.4, 2.5, 1.5])