In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [2]:
a=arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape=2,3

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [10]:
a=arange(3)

In [11]:
shape(a)

(3,)

In [12]:
y=a[newaxis,:]

In [13]:
shape(y)

(1, 3)

In [14]:
y=a[:,newaxis]

In [15]:
shape(y)

(3, 1)

In [16]:
y=a[newaxis,newaxis,:]

In [17]:
shape(y)

(1, 1, 3)

In [20]:
a=arange(6)

In [22]:
a.shape=(2,1,3)

In [23]:
b=a.squeeze()
b.shape

(2, 3)

In [24]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [25]:
a.transpose()  #转置

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [26]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [27]:
a=arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [28]:
a.shape=3,4,5

In [29]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [30]:
b=a.T
b.shape

(5, 4, 3)

In [31]:
a=arange(6)
a.shape=(2,3)

In [32]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
b=a.T
b[0,1]=30

In [34]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [35]:
#数组链接
x=array([[0,1,2],[10,11,12]])
y=array([[50,51,52],[60,61,62]])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [36]:
z=concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [37]:
z.shape

(4, 3)

In [39]:
z=concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [40]:
vstack((x,y)).shape

(4, 3)

In [41]:
hstack((x,y)).shape

(2, 6)

In [42]:
dstack((x,y)).shape

(2, 3, 2)

In [43]:
a=array([[0,1],[2,3]])
b=a.flatten()
b

array([0, 1, 2, 3])

In [44]:
b[0]=10
print(b)
print(a)

[10  1  2  3]
[[0 1]
 [2 3]]


In [45]:
a.flat

In [46]:
b=a.flat

In [47]:
b[0]

0

In [48]:
b[0]=10

In [49]:
print(a)

[[10  1]
 [ 2  3]]


In [50]:
a.flat[:]

array([10,  1,  2,  3])

In [51]:
a=array([[0,1],[2,3]])
b=a.ravel()
b

array([0, 1, 2, 3])

In [52]:
b[0]=10
a

array([[10,  1],
       [ 2,  3]])

In [54]:
a=array([[0,1],[2,3]])
aa=a.transpose()
b=aa.ravel()
b

array([0, 2, 1, 3])

In [55]:
b[0]=10
aa

array([[0, 2],
       [1, 3]])

In [56]:
a

array([[0, 1],
       [2, 3]])

In [58]:
x=1
atleast_1d(x)

array([1])

In [59]:
a=array([1,2,3])
b=atleast_2d(a)
b.shape

(1, 3)

In [60]:
b

array([[1, 2, 3]])

In [61]:
c=atleast_3d(b)

In [62]:
c.shape

(1, 3, 1)