In [1]:
from numpy import *

In [2]:
#复数数组
a=array([1+1j,2,3,4])

In [3]:
a.dtype

dtype('complex128')

In [4]:
a.real#实部

array([1., 2., 3., 4.])

In [5]:
a,imag#虚部

(array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j]),
 <function numpy.lib.type_check.imag(val)>)

In [6]:
a.imag=[1,2,3,4]

In [7]:
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [8]:
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

In [9]:
a=array([0.,1,2,3])

In [10]:
a.dtype

dtype('float64')

In [11]:
a.real

array([0., 1., 2., 3.])

In [12]:
a,imag

(array([0., 1., 2., 3.]), <function numpy.lib.type_check.imag(val)>)

In [13]:
a.conj()

array([0., 1., 2., 3.])

In [16]:
#指定数组类型
a=array([0,1.0,2,3])

In [17]:
a.dtype

dtype('float64')

In [18]:
a.nbytes

32

In [20]:
a=array([0,1.0,2,3],dtype=float32)

In [21]:
a.dtype

dtype('float32')

In [22]:
a.nbytes

16

In [27]:
a = array([0,1,2,3],dtype=uint8)
a.dtype

dtype('uint8')

In [28]:
a = array([102,111,212], dtype=uint8)
a.tofile('foo.dat')

In [29]:
b = frombuffer('foo',dtype=uint8)
b

AttributeError: 'str' object has no attribute '__buffer__'

In [30]:
import os

In [31]:
os.remove('foo.dat')

In [32]:
#查看字符ASCⅡ码值
ord('f')

102

In [33]:
ord('S')

83

In [35]:
a = array([1,1.2,'hello', [10,20,30]], dtype=object)

In [36]:
a*2

array([2, 2.4, 'hellohello', list([10, 20, 30, 10, 20, 30])], dtype=object)

In [37]:
a = array([1.5, -3], dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

In [38]:
asarray(a, dtype=float64)

array([ 1.5, -3. ])

In [39]:
asarray(a, dtype=uint8)

array([  1, 253], dtype=uint8)

In [40]:
a  #不会修改原来的值

array([ 1.5, -3. ], dtype=float32)

In [41]:
b=asarray(a,dtype=float32)

In [42]:
b is a

True

In [43]:
asarray([1,2,3,4])

array([1, 2, 3, 4])

In [44]:
a.astype(float64)

array([ 1.5, -3. ])

In [45]:
a.astype(uint8)

array([  1, 253], dtype=uint8)

In [46]:
a

array([ 1.5, -3. ], dtype=float32)

In [48]:
b=a.astype(float32)

In [49]:
a

array([ 1.5, -3. ], dtype=float32)

In [50]:
b

array([ 1.5, -3. ], dtype=float32)

In [51]:
a is b

False

In [52]:
#view
a = array((1,2,3,4), dtype=int32)
a

array([1, 2, 3, 4])

In [53]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [54]:
a[0]=2**30

In [55]:
a

array([1073741824,          2,          3,          4])

In [56]:
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0],
      dtype=uint8)