In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [2]:
names=array(['bob','sue','jan','ad'])
weights=array([20.8,93.2,53.4,61.8])
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

In [3]:
ordered_indices=argsort(weights)
ordered_indices  #索引

array([0, 2, 3, 1], dtype=int64)

In [4]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [6]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], dtype='<U3')

In [7]:
weights

array([20.8, 93.2, 53.4, 61.8])

In [8]:
data=array([20.8,93.2,53.4,61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

In [9]:
data

array([20.8, 93.2, 53.4, 61.8])

In [10]:
data.sort()

In [11]:
data #data值被改变

array([20.8, 53.4, 61.8, 93.2])

In [12]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [13]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [14]:
sort(a,axis=0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

In [15]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [16]:
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [17]:
from numpy.random import rand
data=rand(100)
data.sort()

In [18]:
data

array([0.00493349, 0.03369062, 0.03379794, 0.04579585, 0.04981957,
       0.0507171 , 0.0694779 , 0.07657936, 0.07768521, 0.0781979 ,
       0.08021842, 0.08263486, 0.08383398, 0.10646301, 0.11739944,
       0.11816812, 0.12066194, 0.12426725, 0.143359  , 0.15487065,
       0.1680705 , 0.18838198, 0.20323717, 0.21449193, 0.22355475,
       0.23723269, 0.24268199, 0.24657091, 0.25675083, 0.25773483,
       0.28001136, 0.29113348, 0.30029744, 0.30142353, 0.32669625,
       0.33455657, 0.33796825, 0.33860103, 0.34129246, 0.35410914,
       0.35962612, 0.38699174, 0.39001403, 0.40401449, 0.41194768,
       0.41935163, 0.42256593, 0.43831829, 0.44603977, 0.4692147 ,
       0.46923056, 0.4738191 , 0.47757588, 0.49884327, 0.50956655,
       0.51554458, 0.52358871, 0.5260775 , 0.53089446, 0.53298804,
       0.53710365, 0.53811386, 0.56088765, 0.56739805, 0.58951578,
       0.59318114, 0.60884582, 0.617857  , 0.62095392, 0.62822389,
       0.64239999, 0.6440485 , 0.64888956, 0.65351982, 0.68482

In [19]:
bounds=.4,.6
bounds

(0.4, 0.6)

In [20]:
low_idx,high_idx=searchsorted(data,bounds)

In [21]:
data[low_idx:high_idx]

array([0.40401449, 0.41194768, 0.41935163, 0.42256593, 0.43831829,
       0.44603977, 0.4692147 , 0.46923056, 0.4738191 , 0.47757588,
       0.49884327, 0.50956655, 0.51554458, 0.52358871, 0.5260775 ,
       0.53089446, 0.53298804, 0.53710365, 0.53811386, 0.56088765,
       0.56739805, 0.58951578, 0.59318114])